### PR TITLE
Bump to latest 0.9.0 of boot2docker

### PR DESCRIPTION
**Pull request by spheromak**
Issue running brew install docker will get you docker 0.11, and the
current dvm boot2docker installs incompatable version of docker under
the hood.

This is optimistic that @mitchellh will pull/rebuild mitchellh/boot2docker-vagrant-box#47

### CODE REVIEW

**Comment by fnichol** [comment]
Looking good, me excite!

**Comment by dweinstein** [comment]
Eagerly awaiting :+1:

**Comment by spheromak** [comment]
I think this is just waiting on a boot2docker from mitchellh to be made. I put up my version on vagrant cloud here: https://vagrantcloud.com/spheromak/boot2docker-0.9.0/version/1 and updated my local Vagrantfile to use them in the interim. @fnichol might make sense for you to manage that for dvm instead of relying on someone elses build ?

**Comment by zaps** [comment]
@spheromak whats the best way to integrate your version into dvm? Replace the override.vm.box_url line in ~/.dvm/Vagrantfile? Will that conflict with other configuration stuff that's already in the file?

Thanks

**Comment by spheromak** [comment]
@zaps I just built my own box and set that as the box to use in
~/.dvm/Vagrantfile

**Comment by zaps** [comment]
@spheromak I tried doing that but `dvm up` seems to hang:

```
==> dvm: Cloning VMware VM: 'boot2docker-0.9.0'. This can take some time...
==> dvm: Verifying vmnet devices are healthy...
==> dvm: Preparing network adapters...
==> dvm: Starting the VMware VM...
==> dvm: Waiting for the VM to finish booting...
```

If I do a `vagrant init boot2docker-0.9.0` and then `vagrant up` the VM boots without hanging, but of course the IP address is not configured to the 192.168.42.43. I have to `vagrant ssh` into the VM, check the IP address, exit the session, then update the DOCKER_HOST. It works, but kind of annoying.

So I think the dvm-provided Vagrantfile configuration is somehow causing a conflict that is preventing the VM from booting.

I don't know if it makes a difference but I'm running the latest version of Vagrant, 1.6.3.

**Comment by fnichol** [comment]
@zaps I was seeing the same last night after upgrading from Vagrant 1.5.4 to 1.6.3. Are you using the vmware_fusion or vmware_workstation provider by chance?

I'm tracking issues upstream in mitchellh/boot2docker-vagrant-box#48 & mitchellh/vagrant#3996

For me, downgrading to Vagrant 1.5.4 resolves this issue.

**Comment by fnichol** [comment]
@spheromak Also thought I'd mention that I'm testing 0.9.1 builds of boot2docker in preparation for an 0.12.0 integration as well. Currently the Mac build of Docker 0.12.0 is having a build issue (tracking dotcloud/docker#6256). Getting there, lots of rough spots at the moment :smile:

**Comment by zaps** [comment]
@fnichol thanks for the pointers to the upstream issues, I'm using the vmware_fusion provider.

For now the workaround I described in my earlier comment is good enough for me, as I need Vagrant 1.6 for it's Windows guest support.

**Comment by fnichol** [comment]
Going to pull this in…and blast on up to 1.0.0, wee!

**Pull request merged**
